global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "sensor-producer"
    static_configs:
      - targets: ["host.docker.internal:8000"]
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: "spark-master"
    static_configs:
      - targets: ["spark-master:8080"]
    metrics_path: /metrics/prometheus

  - job_name: "airflow"
    static_configs:
      - targets: ["airflow-webserver:8080"]
    metrics_path: /admin/metrics
    scrape_interval: 30s
